# Generated by Django 4.1.7 on 2023-03-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
